grimmer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "callbacks" }
  resources :geofences
  resources :bans
  resources :dumpsters
  resources :blacklists
  resources :post_reports
  resources :post_votes
  resources :post_shares
  resources :post_comments
  resources :post_attachments

  defaults format: :json do
    resources :users, :posts
  end
  resources :post
  resources :user_profiles
  resources :users
  delete "users/:id", to: "users#destroy"
  get  "/user_profile/:username" =>"user_profile#username_show"
  resources :home do
    member do
      put "like", to: "home#like"
      put "dislike", to: "home#dislike"
      put "report", to: "home#report"
      put "follow", to: "home#follow"
      delete :delete_attachment
      delete :delete
      delete :delete_comment
      put "comment", to: "home#comment"
      get "edit", to: "home#edit"
      get "edit_comment", to: "home#edit_comment"
      get "map", to: "home#map"
    end
  end
  resources :search
  resources :my_posts
  resources :popular_posts
  resources :admin
  root 'home#index'

  post '/login',   to: 'sessions#create', as: :log_in
  delete '/log_out' => 'sessions#destroy', as: :log_out

  get '/sign_in' => 'registrations#new', as: :registrations
  post '/sign_in' => 'registrations#create', as: :sign_in
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grimmer/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new # for guest
    if user.roles_mask == 0
      can :read, :all #for guest without roles
    elsif user.roles_mask == 1
      just_read
    elsif user.roles_mask == 2
      admin
    elsif user.roles_mask == 3
      superadmin
    end
  end

  def just_read
    can :crud, Post
    can :crud, PostComment
    can :crud, PostVote
    can :crud, PostAttachment
  end

  def admin
    can :manage, [User, Post, Blacklist, Dumpster, UserProfile, PostAttachment, Geofence, Ban]
  end

  def superadmin
    can :manage, :all
  end
end

grimmer/app/models/ban.rb
class Ban < ApplicationRecord
  belongs_to :user
end

grimmer/app/models/blacklist.rb
class Blacklist < ApplicationRecord
  belongs_to :user

  before_create :check_dates
  private
  def check_dates
    if start_date > ending_date
      errors.add(:start_date, "start date must be before ending date")
      return false
    else
      return true
    end
  end
end

grimmer/app/models/dumpster.rb
class Dumpster < ApplicationRecord
  belongs_to :post
end

grimmer/app/models/geofence.rb
class Geofence < ApplicationRecord
  belongs_to :user
end

grimmer/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comment, :dependent => :destroy
  has_many :post_attachment, :dependent => :destroy
  has_many :post_vote, :dependent => :destroy
  has_many :post_report, :dependent => :destroy
  has_many :post_share, :dependent => :destroy
end

grimmer/app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  belongs_to :post
  has_many_attached :avatars

end

grimmer/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user



end

grimmer/app/models/post_report.rb
class PostReport < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/post_share.rb
class PostShare < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/post_vote.rb
class PostVote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :remember_token
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :trackable, :authentication_keys => {email: true, login: false},
         :omniauth_providers => [:google_oauth2]

  has_many :post,  :dependent => :destroy
  has_one :user_profile,  :dependent => :destroy
  has_many :post_comments, :dependent => :destroy
  has_many :post_shares, :dependent => :destroy
  has_many :post_votes, :dependent => :destroy
  has_many :post_reports, :dependent => :destroy
  has_many :blacklists, :dependent => :destroy
  before_create :check_email
  after_create :create_profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.roles_mask = auth.info.roles_mask
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  ROLES = %w[guest user admin superadmin]
  def role?(base_role)
    base_role == ROLES[roles_mask]
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private
  def check_email
    if /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i =~ email
      true
    else
      errors.add(:email, "not a valid email")
      false
    end
  end

  def create_profile
    profile = UserProfile.create(user_id: :id, name: :name)
    unless profile.save
      errors.add(:profile, "Couldn't create profile")
    end
  end
end

grimmer/app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_picture



end

grimmer/app/helpers/admin_helper.rb
module AdminHelper
end

grimmer/app/helpers/bans_helper.rb
module BansHelper
end

grimmer/app/helpers/home_helper.rb
module HomeHelper


  def auto_link_usernames(text)
    text.gsub /(?<=\s|^)@[A-Za-z0-9_]+(?=\b)/ do |username|
      @user_profile = UserProfile.where("username = ?" , username.gsub('@','')).first
      if @user_profile
        link_to(username, user_profile_path(@user_profile), :class => "btn-link inline-button")
      end
    end.html_safe
  end
end

grimmer/app/helpers/my_posts_helper.rb
module MyPostsHelper
  def auto_link_usernames(text)
    text.gsub /(?<=\s|^)@[A-Za-z0-9_]+(?=\b)/ do |username|
      link_to(username, user_profile_path(username.gsub('@', '')))
    end.html_safe
  end
end

grimmer/app/helpers/posts_helper.rb
module PostsHelper
end

grimmer/app/helpers/search_helper.rb
module SearchHelper
end

grimmer/app/helpers/users_helper.rb
module UsersHelper
end

grimmer/app/views/admin/edit.html.erb
<h2>Edit user details</h2>
<div class="container">
  <%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>

    <div class="field">
      <%= form.label :roles_mask %>
      <%= form.text_field :roles_mask %> <br>
      <strong>1: Normal user, 2: Admin, 3: Superadmin</strong>
    </div>

    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>


</div>

grimmer/app/views/admin/show.html.erb
<% content_for :custom_js do %>
  <%= javascript_include_tag "admin_external" %>
<% end %>
<% if User.find_by(id: session["warden.user.user.key"][0][0]).roles_mask != 1 %>
<div class="container" style="margin-top: 45px">
  <strong>admin view</strong>
</div>

<div class="container">
<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'admins')">Admin Management</button>
  <button class="tablinks" onclick="openTab(event, 'dumpster')">Dumpster</button>
  <button class="tablinks" onclick="openTab(event, 'blacklist')">Blacklist</button>
  <button class="tablinks" onclick="openTab(event, 'user_managment')">User Management</button>
</div>

  <div id="admins" class="tabcontent">
    <% if @admins.length == 0%>
    <h4>No admins...</h4>
    <% else %>
      <table class="table table-striped table-bordered" id="admins_table">
        <thead>
          <strong>Admin Managment</strong>
          <tr>
            <th style="text-align: center">Id</th>
            <th style="text-align: center">Email</th>
            <th style="text-align: center">Admin type</th>
            <th style="text-align: center">Last Access</th>
            <th style="text-align: center"></th>
          </tr>
        </thead>
        <tbody id="admins_table_body">
        <% @admins.each do |admin| %>
        <tr>
          <td><% admin.id %></td>
          <td><% admin.email %></td>
          <% if admin.roles_mask == 2 %>
           <td>App admin</td>
          <% elsif admin.roles_mask == 3 %>
            <td>System admin</td>
          <% end %>
          <td><% admin.last_sign_in_at %></td>
          <td>
            <%= link_to "", user_profile_path(id: admin.id), method: :get, class: 'btn btn-sm btn-primary fas fa-eye', title: 'Go to profile' %>
            <%= link_to "", edit_admin_path(id: admin.id), method: :get, class: 'btn btn-sm btn-primary far fa-edit', title: 'Edit' %>
            <%= link_to "", admin, :method => :delete, class: 'btn btn-sm btn-danger far fa-trash-alt', title: 'Delete User', confirm: 'Are you sure?'%>
          </td>
        </tr>
        <% end %>
        </tbody>
      </table>
    <% end %>
  </div>

<div id="dumpster" class="tabcontent">
<% if @dumpster_posts.length == 0%>
  <h4> No posts in the dumpster...</h4>
<% else %>
  <table class="table table-striped table-bordered" id="dumpster_table">
      <thead>
        <strong> Dumpster managment</strong>
      <tr>
          <th style="text-align:center">Post Title</th>
          <th style="text-align:center">Author</th>
          <th style="text-align: center">Email</th>
          <th style="text-align: center"></th>
          <th></th>
      </tr>
      </thead>
      <tbody id="dumpster_table_body">
  <% @dumpster_posts.each do |post| %>
          <tr>
            <% if post.nil? %>
            <% next %>
            <% else %>
            <% owner_user = User.find_by(id: post.user_id) %>
            <td><%= post.title %></td>
            <td><%= owner_user.name %></td>
            <td><%= owner_user.email %></td>
            <td>
              <%= link_to "", post_path(id: post.id), :method => :get, title: "Go to Post", class: "btn btn-sm btn-primary fas fa-eye" %>
              <%= link_to "", dumpster_path(post_id: post.id), :method => :delete, title: "Make visible again", class: 'btn btn-sm btn-primary fas fa-share-square' %>
              <%= link_to "", post_path(id: post.id), :method => :delete, title: "Delete Post", class: "btn btn-sm btn-danger far fa-trash-alt" %>
            </td>
            <% end %>
          </tr>

  <% end %>
  </tbody>
  </table>
<% end %>
</div>

<div id="blacklist" class="tabcontent">
<% if (@blacklist.length == 0)%>
  <h4> No users in the blacklist...</h4>
<% else %>
  <table class="table table-striped table-bordered" id="blacklist_table">
      <thead>
        <strong> Blacklist managment</strong>
      <tr>
          <th style="text-align:center" >Id</th>
          <th style="text-align:center" >Email</th>
          <th></th>
      </tr>
      </thead>
      <tbody id="blacklist_table_body">
      <% @blacklist.each do |user| %>
        <tr>
          <td><%= user[0].id %></td>
          <td><%= user[0].email %></td>
          <td>
            <%= link_to "", blacklist_path(id: user[1]), method: :delete, class: "btn btn-sm btn-primary fas fa-share-square", title: "Take out of the blacklist" %>
            <%= link_to "", user[0], method: :delete, class: 'btn btn-sm btn-danger far fa-trash-alt', title: 'Delete User', confirm: 'Are you sure?'%>
          </td>
        </tr>
      <% end %>
      </tbody>
  </table>
<% end %>
</div>

<div id="user_managment" class="tabcontent">
<table class="table table-striped table-bordered" id="user_table">
    <thead>
      <strong> User managment</strong> <br>
      <%= link_to "New user", new_user_path, method: :get, title: 'Add new user',class: 'btn btn-sm btn-primary fas fa-plus' %> |
      <%= link_to "Blacklist", new_blacklist_path, method: :get, class: 'btn btn-sm btn-warning fas fa-share-square', title: 'Send user to blacklist' %>
      <br><br>
      <tr>
        <th style="text-align: center">Id</th>
        <th style="text-align: center">Email</th>
        <th style="text-align: center">Role</th>
        <th style="text-align: center">Last Access</th>
        <th style="text-align: center"></th>
    </tr>
    </thead>
    <tbody id="user_table_body">
    <% @all_users.each do |user| %>
      <!-- Body -->
      <tr>
        <td id="user-<%= user.id%>"><%= user.id%></td>
        <td><%= user.email%></td>
        <% if user.roles_mask == 1 %>
          <td>Common User</td>
        <% elsif user.roles_mask == 2 %>
          <td>App admin</td>
        <% elsif user.roles_mask == 3 %>
          <td>System admin</td>
        <% end %>
        <td><%= user.last_sign_in_at %></td>
        <td>
          <%= link_to "", user_profile_path(id: user.id), method: :get, class: 'btn btn-sm btn-primary fas fa-eye', title: 'Go to profile' %>
          <%= link_to "", edit_admin_path(id: user.id), method: :get, class: 'btn btn-sm btn-primary far fa-edit', title: 'Edit' %>
          <%= link_to "", user, :method => :delete, class: 'btn btn-sm btn-danger far fa-trash-alt', title: 'Delete User', confirm: 'Are you sure?'%>
        </td>
      </tr>
    <% end %>

    </tbody>
</table>
</div>
</div>
<% else %>
  <div class="container">
    <strong>Insufficient permissions! </strong>
  </div>
<% end %>

grimmer/app/views/admin/show_post.html.erb
<p>
  <strong>User:</strong>
  <%= @post.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>City:</strong>
  <%= @post.city %>
</p>

<p>
  <strong>Country:</strong>
  <%= @post.country %>
</p>

<p>
  <strong>Location:</strong>
  <%= @post.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @post.status %>
</p>

<p>
  <strong>Visibility:</strong>
  <%= @post.visibility %>
</p>

grimmer/app/views/index/login.html.erb
<p>login</p>
<div class="container">
  <h4>Log in</h4>
  <div class="card-body bg-light" style="margin-top: 20px; width: 75%;">
    <form class="form-inline col-lg-12" action="/header.html">
      <div class="input-group  mr-sm-2">
        <div class="input-group-prepend">
          <span class="input-group-text">@</span>
        </div>
        <input type="text" class="form-control" placeholder="Username">
      </div>
      <div class="input-group my-2 my-sm-0">
        <div class="input-group-prepend">
          <span class="input-group-text">*</span>
        </div>
        <input type="password" class="form-control" placeholder="Password">
      </div>
      <button class="btn btn-primary" type="submit">SignIn</button>
    </form>
  </div>
</div>

grimmer/app/views/index/signup.html.erb
<h4>Signup aqui</h4>

grimmer/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GRIMMER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="UTF-8">
    <link rel="app/assets/stylesheet"  href="application.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <script src="js/bootstrap.min.js"></script>


    <link rel="app/assets/stylesheet"  href="application.css" />
    <link rel="stylesheet" href="css/style.css">

    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
    <link rel="icon" href="images/icon.png" type="image/x-icon" />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Custom JS -->
    <%= yield(:custom_js) %>
</head>
  <body style="margin: 0px">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand " href="/home">GRIMMER</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/home"><i class="fa fa-house"></i>Home <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
      </form>
    </div>
  </nav>

  <div class="container" style="margin-top: 30px">
    <div class="row">
      <div class="col-2"></div>
      <div class="col-8">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

grimmer/app/views/layouts/google_logged_in.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GRIMMER</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta charset="UTF-8">
  <link rel="app/assets/stylesheet"  href="application.css" />
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <link rel="stylesheet" href="css/bootstrap.min.css">
  <script src="js/bootstrap.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="//maps.google.com/maps/api/js?key=[AIzaSyCUgEHrNWIUC-GBayNiJrJZ9_yC3hdWd2Q]"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>



  <link rel="app/assets/stylesheet"  href="application.css" />
  <link rel="stylesheet" href="css/style.css">

  <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  <link rel="icon" href="images/icon.png" type="image/x-icon" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!-- Custom JS -->
  <%= yield(:custom_js) %>
</head>

<body style="margin: 0px">
<nav class="navbar navbar-expand-md bg-dark navbar-dark sticky-top">
  <a class="navbar-brand">GRIMMER</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navb" aria-expanded="true">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div id="navb" class="navbar-collapse collapse hide">
    <%if User.find_by(id: session["warden.user.user.key"][0][0])%>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/home"><i class="fa fa-house"></i>Home <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <% if UserProfile.find_by(user_id: session["warden.user.user.key"][0][0]) %>
            <%= link_to "My Profile", user_profile_path(:id => session["warden.user.user.key"][0][0]), method: :get, :class=>"nav-link" %>
          <% else %>
            <%= link_to "Create Profile", new_user_profile_path, :class => "nav-link" %>
          <% end %>
        </li>

        <li class="nav-item">
          <a class="nav-link " href="/my_posts">My Posts</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href="/popular_posts">Popular Posts</a>
        </li>
        <% if User.find_by(id: session["warden.user.user.key"][0][0]).roles_mask.to_i != 1%>
          <li class="nav-item">
            <%= link_to "Admin Tools", admin_path(:id => session["warden.user.user.key"][0][0]), method: :get, :class =>"nav-link" %>
          </li>
        <% end %>
      </ul>
      <div class="form-inline">
        <%= form_tag search_path(id: session['warden.user.user.key'][0][0]), :method => :get do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search something...", class: "form-control"%>
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        <% end %>
      </div>
      <%= link_to "Log Out", log_out_path, method: :delete, :class=>"nav-link" %>
  <%end %>

  </div>
</nav>
<div class="container" style="margin-top: 30px">
  <div class="row">
    <div class="col-2"></div>
    <div class="col-8">
      <strong><%= current_user %></strong>
    </div>
  </div>
</div>

<div class="container" style="margin-top: 30px">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <%= yield %>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>