grimmer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "callbacks" }
  resources :geofences
  resources :bans
  resources :dumpsters
  resources :blacklists
  resources :post_reports
  resources :post_votes
  resources :post_shares
  resources :post_comments
  resources :post_attachments

  defaults format: :json do
    resources :users, :posts
  end
  resources :post
  resources :user_profiles
  resources :users
  delete "users/:id", to: "users#destroy"
  get  "/user_profile/:username" =>"user_profile#username_show"
  resources :home do
    member do
      put "like", to: "home#like"
      put "dislike", to: "home#dislike"
      put "report", to: "home#report"
      put "follow", to: "home#follow"
      delete :delete_attachment
      delete :delete
      delete :delete_comment
      put "comment", to: "home#comment"
      get "edit", to: "home#edit"
      get "edit_comment", to: "home#edit_comment"
      get "map", to: "home#map"
    end
  end
  resources :search
  resources :my_posts
  resources :popular_posts
  resources :admin
  root 'home#index'

  post '/login',   to: 'sessions#create', as: :log_in
  delete '/log_out' => 'sessions#destroy', as: :log_out

  get '/sign_in' => 'registrations#new', as: :registrations
  post '/sign_in' => 'registrations#create', as: :sign_in
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grimmer/app/models/geofence.rb
class Geofence < ApplicationRecord
  belongs_to :user
end

grimmer/app/controllers/geofences_controller.rb
class GeofencesController < ApplicationController
  before_action :set_geofence, only: [:show, :edit, :update, :destroy]

  # GET /geofences
  # GET /geofences.json
  def index
    @geofences = Geofence.all
  end

  # GET /geofences/1
  # GET /geofences/1.json
  def show
  end

  # GET /geofences/new
  def new
    @geofence = Geofence.new
  end

  # GET /geofences/1/edit
  def edit
  end

  # POST /geofences
  # POST /geofences.json
  def create
    session[:return_to] ||= request.referer
    param = params[:geofence]
    @geofence = Geofence.new(user_id: param[:user_id], post_id: param[:post_id], latitude: param[:latitude],
                             longitude: param[:longitude],region: param[:region])
    if param[:post_id] != ""
    post = Post.find(param[:post_id])

    respond_to do |format|
      if @geofence.save
        format.html { redirect_to edit_home_path(post) , notice: 'Geofence was successfully created.' }
        format.json { render :show, status: :created, location: @geofence }
      else
        format.html { render :new }
        format.json { render json: @geofence.errors, status: :unprocessable_entity }
      end
    end
    else
      @user_profile = UserProfile.find(session["warden.user.user.key"][0][0])
      respond_to do |format|
        if @geofence.save
          format.html { redirect_to edit_user_profile_path(@user_profile) , notice: 'Geofence was successfully created.' }
          format.json { render :show, status: :created, location: @geofence }
        else
          format.html { render :new }
          format.json { render json: @geofence.errors, status: :unprocessable_entity }
        end
      end
      end
  end

  # PATCH/PUT /geofences/1
  # PATCH/PUT /geofences/1.json
  def update
    respond_to do |format|
      if @geofence.update(geofence_params)
        if params[:geofence][:post_id] != ""
        post = Post.find(params[:geofence][:post_id])
        format.html { redirect_to edit_home_path(post), notice: 'Geofence was successfully updated.' }
        format.json { render :show, status: :ok, location: @geofence }
        else
          @user_profile = UserProfile.find(session["warden.user.user.key"][0][0])
          format.html { redirect_to edit_user_profile_path(@user_profile), notice: 'Geofence was successfully updated.' }
          format.json { render :show, status: :ok, location: @geofence }
          end

      else
        format.html { render :edit }
        format.json { render json: @geofence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geofences/1
  # DELETE /geofences/1.json
  def destroy
    @geofence.destroy
    respond_to do |format|
      format.html { redirect_to geofences_url, notice: 'Geofence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geofence
      @geofence = Geofence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geofence_params
      params.require(:geofence).permit(:user_id, :region, :latitude, :longitude, :post_id)
    end
end

grimmer/app/helpers/geofences_helper.rb
module GeofencesHelper
end

grimmer/app/views/geofences/_form.html.erb
<meta name='turbolinks-visit-control' content='reload'>
<%= form_with(model: geofence, local: true) do |form| %>
  <% if geofence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(geofence.errors.count, "error") %> prohibited this geofence from being saved:</h2>

      <ul>
      <% geofence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :user_id, value: session["warden.user.user.key"][0][0], type:"hidden" %>
    <%= form.text_field :post_id, value: params[:post_id], type:"hidden" %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= form.text_field :region %>
  </div>

  <div class="field" >
    <%= form.label :latitude %>
    <%= form.text_field :latitude , id:"place_latitude"%>
  </div>
  <div class="field" >
    <%= form.label :longitude %>
    <%= form.text_field :longitude ,id:"place_longitude"%>
  </div>
  <meta name='turbolinks-visit-control' content='reload'>
  <script>
      document.addEventListener("DOMContentLoaded", initMap);
  </script>

  <div id="map" style='width: 800px; height: 400px;'></div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<script>
function initMap() {
<%geo = Geofence.where("post_id  =?",params[:id]).first %>

var lat = document.getElementById('place_latitude').value;
var lng = document.getElementById('place_longitude').value;
if (!lat || !lng){
    <%if geo %>
lat=<%=geo.latitude %>;
lng=<%=geo.longitude %>;
<%else %>
    lat = 0;
    lng =  10;
    <%end %>
document.getElementById('place_latitude').value = lat;
document.getElementById('place_longitude').value = lng;
}

var myCoords = new google.maps.LatLng(lat, lng);
var mapOptions = {
center: myCoords,
zoom: 14
};
var map = new google.maps.Map(document.getElementById('map'), mapOptions);
var marker = new google.maps.Marker({
position: myCoords,
animation: google.maps.Animation.DROP,
map: map,
draggable: true
});
    function refreshMarker(){
        var lat = document.getElementById('place_latitude').value;
        var lng = document.getElementById('place_longitude').value;
        var myCoords = new google.maps.LatLng(lat, lng);
        marker.setPosition(myCoords);
        map.setCenter(marker.getPosition());
    }
// when input values change call refreshMarker
    document.getElementById('place_latitude').onchange = refreshMarker;
    document.getElementById('place_longitude').onchange = refreshMarker;

    marker.addListener('drag', function() {
        latlng = marker.getPosition();
        newlat=(Math.round(latlng.lat()*1000000))/1000000;
        newlng=(Math.round(latlng.lng()*1000000))/1000000;
        document.getElementById('place_latitude').value = newlat;
        document.getElementById('place_longitude').value = newlng;
    });
// When drag ends, center (pan) the map on the marker position
    marker.addListener('dragend', function() {
        map.panTo(marker.getPosition());
    });


}

// refresh marker position and recenter map on marker

</script>
<style>
  #map {
    height: 400px;
    width: 100%;
  }
</style>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB_AvqTAYSLAaa0Xd3FzNTfWG03cQWRpN4&callback=initMap">
</script>

grimmer/app/views/geofences/edit.html.erb
<h1>Editing Geofence</h1>

<%= render 'form', geofence: @geofence %>

<%= link_to 'Show', @geofence %> |
<%= link_to 'Back', geofences_path %>

grimmer/app/views/geofences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Geofences</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Region</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @geofences.each do |geofence| %>
      <tr>
        <td><%= geofence.user %></td>
        <td><%= geofence.region %></td>
        <td><%= link_to 'Show', geofence %></td>
        <td><%= link_to 'Edit', edit_geofence_path(geofence) %></td>
        <td><%= link_to 'Destroy', geofence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Geofence', new_geofence_path %>

grimmer/app/views/geofences/new.html.erb
<h1>New Geofence</h1>

<%= render 'form', geofence: @geofence %>

<%= link_to 'Back', geofences_path %>

grimmer/app/views/geofences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @geofence.user %>
</p>

<p>
  <strong>Region:</strong>
  <%= @geofence.region %>
</p>

<%= link_to 'Edit', edit_geofence_path(@geofence) %> |
<%= link_to 'Back', geofences_path %>