grimmer/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { :omniauth_callbacks => "callbacks" }
  resources :geofences
  resources :bans
  resources :dumpsters
  resources :blacklists
  resources :post_reports
  resources :post_votes
  resources :post_shares
  resources :post_comments
  resources :post_attachments

  defaults format: :json do
    resources :users, :posts
  end
  resources :post
  resources :user_profiles
  resources :users
  delete "users/:id", to: "users#destroy"
  get  "/user_profile/:username" =>"user_profile#username_show"
  resources :home do
    member do
      put "like", to: "home#like"
      put "dislike", to: "home#dislike"
      put "report", to: "home#report"
      put "follow", to: "home#follow"
      delete :delete_attachment
      delete :delete
      delete :delete_comment
      put "comment", to: "home#comment"
      get "edit", to: "home#edit"
      get "edit_comment", to: "home#edit_comment"
      get "map", to: "home#map"
    end
  end
  resources :search
  resources :my_posts
  resources :popular_posts
  resources :admin
  root 'home#index'

  post '/login',   to: 'sessions#create', as: :log_in
  delete '/log_out' => 'sessions#destroy', as: :log_out

  get '/sign_in' => 'registrations#new', as: :registrations
  post '/sign_in' => 'registrations#create', as: :sign_in
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

grimmer/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user = user || User.new # for guest
    if user.roles_mask == 0
      can :read, :all #for guest without roles
    elsif user.roles_mask == 1
      just_read
    elsif user.roles_mask == 2
      admin
    elsif user.roles_mask == 3
      superadmin
    end
  end

  def just_read
    can :crud, Post
    can :crud, PostComment
    can :crud, PostVote
    can :crud, PostAttachment
  end

  def admin
    can :manage, [User, Post, Blacklist, Dumpster, UserProfile, PostAttachment, Geofence, Ban]
  end

  def superadmin
    can :manage, :all
  end
end

grimmer/app/models/ban.rb
class Ban < ApplicationRecord
  belongs_to :user
end

grimmer/app/models/blacklist.rb
class Blacklist < ApplicationRecord
  belongs_to :user

  before_create :check_dates
  private
  def check_dates
    if start_date > ending_date
      errors.add(:start_date, "start date must be before ending date")
      return false
    else
      return true
    end
  end
end

grimmer/app/models/dumpster.rb
class Dumpster < ApplicationRecord
  belongs_to :post
end

grimmer/app/models/geofence.rb
class Geofence < ApplicationRecord
  belongs_to :user
end

grimmer/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :post_comment, :dependent => :destroy
  has_many :post_attachment, :dependent => :destroy
  has_many :post_vote, :dependent => :destroy
  has_many :post_report, :dependent => :destroy
  has_many :post_share, :dependent => :destroy
end

grimmer/app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
  belongs_to :post
  has_many_attached :avatars

end

grimmer/app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :post
  belongs_to :user



end

grimmer/app/models/post_report.rb
class PostReport < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/post_share.rb
class PostShare < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/post_vote.rb
class PostVote < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

grimmer/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  attr_accessor :remember_token
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, :trackable, :authentication_keys => {email: true, login: false},
         :omniauth_providers => [:google_oauth2]

  has_many :post,  :dependent => :destroy
  has_one :user_profile,  :dependent => :destroy
  has_many :post_comments, :dependent => :destroy
  has_many :post_shares, :dependent => :destroy
  has_many :post_votes, :dependent => :destroy
  has_many :post_reports, :dependent => :destroy
  has_many :blacklists, :dependent => :destroy
  before_create :check_email
  after_create :create_profile

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
      user.roles_mask = auth.info.roles_mask
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  ROLES = %w[guest user admin superadmin]
  def role?(base_role)
    base_role == ROLES[roles_mask]
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
               BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private
  def check_email
    if /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i =~ email
      true
    else
      errors.add(:email, "not a valid email")
      false
    end
  end

  def create_profile
    profile = UserProfile.create(user_id: :id, name: :name)
    unless profile.save
      errors.add(:profile, "Couldn't create profile")
    end
  end
end

grimmer/app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
  has_one_attached :profile_picture



end

grimmer/app/controllers/search_controller.rb
class SearchController < ApplicationController
  def show
    if params[:search].blank?
      redirect_to(root_path, alert: "Search field empty!")
    else
      @users = User.where(["name LIKE ?", "%#{params[:search]}%"])
      @posts = Post.where(["title or description LIKE ?", "%#{params[:search]}%"] )
    end
  end
end

grimmer/app/helpers/admin_helper.rb
module AdminHelper
end

grimmer/app/helpers/bans_helper.rb
module BansHelper
end

grimmer/app/helpers/home_helper.rb
module HomeHelper


  def auto_link_usernames(text)
    text.gsub /(?<=\s|^)@[A-Za-z0-9_]+(?=\b)/ do |username|
      @user_profile = UserProfile.where("username = ?" , username.gsub('@','')).first
      if @user_profile
        link_to(username, user_profile_path(@user_profile), :class => "btn-link inline-button")
      end
    end.html_safe
  end
end

grimmer/app/helpers/my_posts_helper.rb
module MyPostsHelper
  def auto_link_usernames(text)
    text.gsub /(?<=\s|^)@[A-Za-z0-9_]+(?=\b)/ do |username|
      link_to(username, user_profile_path(username.gsub('@', '')))
    end.html_safe
  end
end

grimmer/app/helpers/posts_helper.rb
module PostsHelper
end

grimmer/app/helpers/search_helper.rb
module SearchHelper
end

grimmer/app/helpers/sessions_helper.rb
module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:current_user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:current_user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # Returns the current logged-in user (if any).
  def current_user
    if (user_id = session[:current_user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:current_user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  # Logs out the current user.
  def log_out
    session["warden.user.user.key"][0][0] = 0
    forget(current_user)
    session.delete(:current_user_id)
    @current_user = session[:current_user_id] = nil
  end

  def forget(user)
    #user.forget
    cookies.delete(:current_user_id)
    cookies.delete(:remember_token)
  end

end

grimmer/app/helpers/users_helper.rb
module UsersHelper
end

grimmer/app/views/search/show.html.erb
<style>
  .fakeimg {
    height: 20px;
    width: 20px;
    background: #aaa;
  }
</style>

<strong>View in progress!</strong>

<div class="container" style="display: flex">
  <div id="users" style="width: 50%">
    <h2>User matches</h2>
  <% @users.each do |user| %>

      <% if user.id == session['warden.user.user.key'][0][0] %>
        <% next %>
      <% end %>
    <div class="form-inline">
    <% profile = UserProfile.find_by_user_id(user.id) %>
      <% if !profile.profile_picture.attached? %>
        <div class="fakeimg"></div>
      <% else %>
        <%=image_tag(profile.profile_picture.variant(resize: "20x20>").processed)%>
      <% end %>
    <%= link_to user.name, user_profile_path(id: user.id), class: "btn btn-outline nav-link inline-button" %>
    </div>
  <% end %>
  </div>
  <div id="posts" style="width: 50%">
    <h2>Posts matches</h2>
    <% @posts.each do |post| %>
      <%if post.user_id != session["warden.user.user.key"][0][0] and post.visibility= true %>
        <div class="card-header">
          <h6 style="text-align: right"><%= post.updated_at%></h6>
          <div>
            <button class="btn btn-link" style="float: right">location</button>
            <%name_user = UserProfile.select("name").where("user_id=?", post.user_id)[0].name + " " + UserProfile.select("last_name").where("user_id=?", post.user_id)[0].last_name%>
            <h5><%= link_to name_user, user_profile_path(:id => post.user_id, method: :get, :class=>"btn-primary" )%></h5>
          </div>
        </div>
        <div class="card-body bg-light">
          <h2><%= post.title%></h2>
          <p><%=post.description %></p>
          <div >
            <%p_a = PostAttachment.where("post_id = ?",post.id) %>
            <%p_a.each do| a|%>
              <% for av in a.avatars do %>

                <%name = av.blob.filename.to_s %>
                <%if name.include? "jpg" or name.include? "png" or name.include? "jpeg"%>
                  <%= link_to url_for(av) do%>
                    <%=image_tag( av.variant(resize: "200x200>").processed, style: "margin:7px",:class=>"nav-link" )%>
                  <%end %>
                <%end %>
              <%end %>
              </div>
              <div>
                <% for av in a.avatars do %>
                  <%name = av.blob.filename.to_s %>
                  <%if !(name.include? "jpg" or name.include? "png" or name.include? "jpeg")%>
                    <%= link_to(name, rails_blob_path(av, disposition: "attachment"),style: "margin:5px") %>
                  <%end %>

                <%end %>
            <%end %>
            </div>
            <div style="margin-top: 15px" >
              <%= link_to  like_home_path(post), class: 'vote  btn btn-info btn-sm', method: :put, remote: true do%>
                <button class="btn  btn-sm btn-like" id="like-post-<%=post.id %>"><%=PostVote.where("post_id = ? AND vote = ?",post.id,true).count %> Like</button>
              <%end %>
              <%= link_to  dislike_home_path(post), class: 'downvote  btn btn-sm btn-info', method: :put, remote: true do%>
                <button class="btn btn-sm btn-dislike" id="dislike-post-<%=post.id %>"><%=PostVote.where("post_id = ? AND vote = ?",post.id,false).count %> DisLike</button>
              <%end %>
              <%= link_to report_home_path(post),method: :put, remote: true, class: " report btn btn-info btn-sm"  do%>
                <button class="btn btn-sm btn-info">Report</button>
              <%end %>
              <%= link_to follow_home_path(post),method: :put, remote: true, class: " follow btn btn-info btn-sm"  do%>
                <button class="btn btn-sm btn-info">Follow</button>
              <%end %>
            </div>
            <div class="form-inline">
              <%= bootstrap_form_tag(:model=> @post_comment,:url =>comment_home_path(post), method: :put, remote: true, html: { multipart: true }) do |f| %>
                <div class="input-group " style="margin-top:30px; flex: 1 1 auto; width:420px">
                  <%= f.text_field :comment, placeholder: "Comment",hide_label: :true , control_col: "col-12", class: "comment-field" %>
                  <div class="input-group-append">
                    <%= f.hidden_field :post_id, :value => post.id %>
                    <%= f.hidden_field :user_id, :value => session["warden.user.user.key"][0][0] %>
                    <%= f.button :submit, label: "Comment", class: " btn btn-success post-comment" %>
                    <%= %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="comment-tread" id="post-comment-<%=post.id%>">
              <%comments = PostComment.where("post_id", post.id ) %>
              <%comments.each do |comment| %>
                <%if(comment.post_id == post.id) %>
                  <div class=" card card-body " style="margin-top:10px">
                    <h5><%=UserProfile.select("name").where("user_id =?", comment.user_id)[0].name %> <%=UserProfile.select("last_name").where("user_id =?", comment.user_id)[0].last_name %>:</h5><%=auto_link_usernames(comment.comment) %>
                    <%if comment.user_id ==session["warden.user.user.key"][0][0]  %>
                      <div>
                        <%= link_to "Edit", edit_comment_home_path(comment), :method => :get, class: "btn btn-sm btn-info float-right" %>
                        <%= link_to "Delete", delete_comment_home_path(comment), :method => :delete, class: "btn btn-sm btn-info float-right",:confirm => "Are you sure?" %>
                      </div>
                    <%end %>
                  </div>
                <%end %>
              <%end %>
            </div>
            </div>
        <br>
      <%else %>
        <div class="card-header">
          <h6 style="text-align: right"><%= post.updated_at%></h6>
          <div>
            <button class="btn btn-link" style="float: right">location</button>
            <% name_user = UserProfile.select("name").where("user_id=?", post.user_id)[0].name.to_s + " " + UserProfile.select("last_name").where("user_id=?", post.user_id)[0].last_name%>
            <h5><%= link_to name_user, user_profile_path(:id => post.user_id, method: :get, :class=>"btn-primary" )%></h5>
          </div>
        </div>
        <div class="card-body bg-light">
          <h2><%= post.title%></h2>
          <p><%= post.description %></p>
          <div >
            <%p_a = PostAttachment.where("post_id = ?",post.id) %>
            <%p_a.each do| a|%>
              <% for av in a.avatars do %>
                <%name = av.blob.filename.to_s %>
                <%if name.include? "jpg" or name.include? "png" or name.include? "jpeg"%>
                  <%= link_to url_for(av) do%>
                    <%=image_tag( av.variant(resize: "200x200>").processed, style: "margin:7px",:class=>"nav-link" )%>
                  <%end %>
                <%end %>
              <%end %>
              </div>
              <div>
                <% for av in a.avatars do %>
                  <%name = av.blob.filename.to_s %>
                  <%if !(name.include? "jpg" or name.include? "png" or name.include? "jpeg")%>
                    <%= link_to(name, rails_blob_path(av, disposition: "attachment"),style: "margin:5px") %>
                  <%end %>

                <%end %>
            <%end %>
            </div>
            <div style="margin-top: 15px" >
              <%= link_to  like_home_path(post), class: 'vote  btn btn-sm btn-info', method: :put, remote: true do%>
                <button class="btn btn-sm btn-like" id="like-post-<%=post.id %>"><%=PostVote.where("post_id = ? AND vote = ?",post.id,true).count %> Like</button>
              <%end %>
              <%= link_to  dislike_home_path(post), class: 'downvote  btn btn-sm btn-info', method: :put, remote: true do%>
                <button class="btn btn-sm btn-dislike" id="dislike-post-<%=post.id %>"><%=PostVote.where("post_id = ? AND vote = ?",post.id,false).count %> DisLike</button>
              <%end %>
              <%= link_to "Edit", edit_home_path(post), :method => :get, class: "btn btn-info btn-edit" %>
              <%= link_to 'Delete Post', delete_home_path(post), :method => :delete, class: "btn btn-info btn-destoy",:confirm => "Are you sure?" %>
            </div>
            <div class="form-inline">
              <%= bootstrap_form_tag(:model=> @post_comment,:url =>comment_home_path(post), method: :put, remote: true, html: { multipart: true }) do |f| %>
                <div class="input-group " style="margin-top:30px; flex: 1 1 auto; width:420px">
                  <%= f.text_field :comment, placeholder: "Comment",hide_label: :true , control_col: "col-12", class: "comment-field" %>
                  <div class="input-group-append">
                    <%= f.hidden_field :post_id, :value => post.id %>
                    <%= f.hidden_field :user_id, :value => session["warden.user.user.key"][0][0] %>
                    <%= f.button :submit, label: "Comment", class: " btn btn-success post-comment" %>
                    <%= %>
                  </div>
                </div>
              <% end %>
            </div>
            <div class="comment-tread" id="post-comment-<%=post.id%>">
              <%comments = PostComment.where("post_id", post.id ) %>
              <%comments.each do |comment| %>
                <%if(comment.post_id == post.id) %>

                  <div class=" card card-body " style="margin-top:10px">
                    <%name_user = UserProfile.select("name").where("user_id=?", comment.user_id)[0].name + " " + UserProfile.select("last_name").where("user_id=?", post.user_id)[0].last_name%>
                    <h5><%= link_to name_user, user_profile_path(:id => comment.user_id, method: :get, :class=>"btn-primary" )%>:</h5><%=auto_link_usernames(comment.comment) %>
                    <%if comment.user_id ==session["warden.user.user.key"][0][0]  %>
                      <div>
                        <%= link_to "Edit", edit_comment_home_path(comment), :method => :get, class: "btn btn-sm btn-info float-right" %>
                        <%= link_to "Delete", delete_comment_home_path(comment), :method => :delete, class: "btn btn-sm btn-info float-right",:confirm => "Are you sure?" %>
                      </div>
                    <%end %>
                  </div>

                <%end %>
              <%end %>
            </div>
            </div>
        <br>
      <%end %>
    <%end %>
  </div>
</div>